env: development # | production
postgres:
  username: postgres
  password: postgres
  sslMode: disable
  host: db
  port: 5432
  dbName: pcs
auth:
  expireAccessToken: 3d
  expireRefreshToken: 6d
  secret: secret
